### PR TITLE
update 开发使用说明 & VS Code 下代码高亮

### PR DESCRIPTION
**Pull request by brucx**

### CODE REVIEW

**Comment by galendai** [comment]
the <font> tag is not closed at **README.md - Line: 53**. 

this breaks rest of the doc's font color. =_=

**Comment by brucx** [comment]
@galendai so 尴尬... 已提交PR #294

**Comment by brucx** [comment]
commit 13594b5c0312f01b470bc8976f6152aba6e08da8 
@afeiship

**Comment by Gcaufy** [comment]
@brucx sorry, thx

**Pull request merged**
